InteliJR/Imobiliaria

docs/docs/Entendimento do problema/rf_rnf.md
- Add 36 functional requirements
- Add 10 non-functional requirements
Closes #5
=> Documentation | Requisitos Funcionais e Não Funcionais

docs/docs/Entendimento do problema/escolha_tecnologias.md
Essa branch adiciona as informações usadas para basear a escolha das tecnologias.
=> Documentation: escolha de tecnologias

docs/docs/Entendimento do problema/servicos-pagamento.md
Fiz aqui a analise com as taxas, vantagens e desvantagens dos principais serviços de pagamento.
=> Analise de serviços de pagamento

docs/docs/Entendimento do problema/rf_rnf.md, docs/docs/Entendimento do problema/user_stories.md
Atualizei os requisitos baseado na discussão que tivemos com a KK. Isso inclui remover, rescrever e adicionar novos requisitos.
=> Requisitos funcionais atualizados

src/Template-service/Auth-service.sln, src/Template-service/ClassLibrary1/Class1.cs, src/Template-service/ClassLibrary1/ClassLibrary1.csproj, src/Template-service/Layer.Application/Controllers/CountryController.cs, src/Template-service/Layer.Application/Controllers/UserController.cs, src/Template-service/Layer.Application/Controllers/UserServiceControler.cs, src/Template-service/Layer.Application/Layer.Application.csproj, src/Template-service/Layer.Application/Models/LoginModel.cs, src/Template-service/Layer.Application/Models/NewLocadorModel.cs, src/Template-service/Layer.Application/Models/NewUserModel.cs, src/Template-service/Layer.Application/Models/UpdateLocadorModel.cs, src/Template-service/Layer.Application/Models/UserLoginModel.cs, src/Template-service/Layer.Application/Program.cs, src/Template-service/Layer.Application/Properties/launchSettings.json, src/Template-service/Layer.Application/appsettings.json, src/Template-service/Layer.Domain/DTO/CountryApiResponseDTO.cs, src/Template-service/Layer.Domain/Entities/JwtSettings.cs, src/Template-service/Layer.Domain/Entities/User.cs, src/Template-service/Layer.Domain/Enums/Roles.cs, src/Template-service/Layer.Domain/Interfaces/ICountryService.cs, src/Template-service/Layer.Domain/Interfaces/ITokenService.cs, src/Template-service/Layer.Domain/Interfaces/IUserService.cs, src/Template-service/Layer.Domain/Layer.Domain.csproj, src/Template-service/Layer.Infrastructure/Database/ApplicationDbContext.cs, src/Template-service/Layer.Infrastructure/Layer.Infrastructure.csproj, src/Template-service/Layer.Infrastructure/ServicesExternal/CountryService.cs, src/Template-service/Layer.Infrastructure/ServicesInternal/TokenService.cs, src/Template-service/Layer.Services/Layer.Services.csproj, src/Template-service/Layer.Services/Services/UserService.cs
Serviços de tempalte com tudo configurado e com exemplo
=> Template de Serviço

src/Auth-service/Dockerfile, src/Auth-service/Layer.Application/Program.cs, src/docker-compose.yml, src/frontend/Dockerfile
- Criação do dockerfile para o frontend
- Criação do docker compose com o serviço de gestão de usuario e front
closes #164
=> Dockerizacao do Front + Docker Compose

src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/pages/Landing.tsx, src/frontend/src/pages/Login.tsx, src/frontend/src/services/apiService.ts, src/frontend/src/services/axiosConfig.ts
- Troca do fetch por axios
- Logica da função para devolver os ips dos serviços
- Intercepter do axios para enviar o token no header automaticamente nas rotas
=> feat: axios + logica de pegar rotas + axios intercepter

src/frontend/src/desktop/pages/NotFound.tsx, src/frontend/src/main.tsx, src/frontend/tailwind.config.js
- Adiciona tela de NotFound - RESPONSIVA
- Adiciona rota geral para redirecionar para a tela 404 caso não encontre mais nenhuma
- Adiciona cores no tailwind
=> FEAT | Not Found Page

src/Auth-service/Dockerfile, src/Gateway/Dockerfile, src/Gateway/DockerfileDev, src/Gateway/nginx.conf, src/Gateway/nginxDev.conf, src/docker-compose.yml
- Configuração do NGINX para deploy e teste local
- Criação dos Dockerfiles para NGINX
- Adição da imagem do NGINX no docker-compose
closes #181
=>  FEATURE | Gateway

src/Payment-service/Dockerfile, src/Payment-service/Layer.Application/Controllers/LogsController.cs, src/Payment-service/Layer.Application/Controllers/PaymentController.cs, src/Payment-service/Layer.Application/Layer.Application.csproj, src/Payment-service/Layer.Application/Program.cs, src/Payment-service/Layer.Domain/Entities/Log.cs, src/Payment-service/Layer.Domain/Entities/MongoDbSettings.cs, src/Payment-service/Layer.Domain/Enums/Roles.cs, src/Payment-service/Layer.Domain/Layer.Domain.csproj, src/Payment-service/Layer.Infrastructure/Database/ApplicationLog.cs, src/Payment-service/Layer.Infrastructure/Layer.Infrastructure.csproj
- Adiciona servico de logs aos casos de uso de pagamentos
- Corrige estruturas de prod/dev
- ajuste de roles
closes: #154
=> feat: adiciona servico de logs ao servico de pagamentos

src/Auth-service/Layer.Application/Controllers/LocadorController.cs, src/Gateway/nginx.conf, src/Gateway/nginxDev.conf, src/Payment-service/Dockerfile, src/Payment-service/Layer.Application/Controllers/PaymentController.cs, src/Payment-service/Layer.Application/Program.cs, src/Payment-service/Layer.Domain/Entities/Payment.cs, src/Payment-service/Layer.Domain/Enums/Roles.cs, src/Property-service/.gitignore, src/Property-service/Dockerfile, src/Property-service/Layer.Application/Program.cs, src/Property-service/Layer.Insfrastructure/Database/ApplicationDbContext.cs, src/docker-compose.yml
- Arrumando docker compose com os serviços de Property e Payment
- Colocando configurações no gateway serviços de Property e Payment (dev e prod)
- Arrumando as portas no serviço dos dockerfiles dos serviços
- Algumas alterações no serviço de pagamento porque não tava rodando
closes #209
=> Colocando serviços de Property e Payment no gateway

src/Auth-service/Layer.Application/Controllers/UserController.cs, src/Auth-service/Layer.Application/Program.cs, src/Gateway/nginxDev.conf, src/frontend/src/mobile/pages/AlterarSenha.tsx, src/frontend/src/mobile/pages/Login.tsx, src/frontend/src/services/axiosConfig.ts
- Alteração na rota AlterarSenhaUsuario do auth-service para pegar o email pelo JWT
- Arrumando CORS do auth service
- Tirar config de CORS no nginx porque tava dando erro de duplicidade de CORS
- Integração da tela mobile AlterarSenha.tsx
- Arrumando tela de login
- Deixando rota do gateway como padrão no front na config do Axios
close #221
=> Integrar tela de alterar senha

src/Auth-service/Layer.Application/Controllers/AccountController.cs, src/Auth-service/Layer.Application/Controllers/ColaboradorController.cs, src/Auth-service/Layer.Application/Controllers/EmailController.cs, src/Auth-service/Layer.Application/Controllers/LocadorController.cs, src/Auth-service/Layer.Application/Controllers/LocatarioController.cs, src/Auth-service/Layer.Application/Controllers/UserController.cs, src/Auth-service/Layer.Application/Models/ColaboradorUserModel.cs, src/Auth-service/Layer.Application/Models/NoColaboradorUserModel.cs, src/Auth-service/Layer.Application/Models/UpdateColaboradorModel.cs, src/Auth-service/Layer.Domain/Entities/Colaborador.cs, src/Auth-service/Layer.Domain/Entities/Locador.cs, src/Auth-service/Layer.Domain/Entities/Locatario.cs, src/Auth-service/Layer.Domain/Entities/User.cs, src/Auth-service/Layer.Domain/Entities/UserDetailsModel.cs, src/Auth-service/Layer.Domain/Interfaces/IEmailSender.cs, src/Auth-service/Layer.Domain/Interfaces/IUserService.cs, src/Auth-service/Layer.Infrastructure/Database/ApplicationDbContext.cs, src/Auth-service/Layer.Services/Services/EmailSenderService.cs, src/Auth-service/Layer.Services/Services/UserService.cs, src/Property-service/Layer.Application/Program.cs, src/docker-compose.yml, src/frontend/src/mobile/components/Form/FormField.tsx, src/frontend/src/mobile/components/Form/FormFieldFilter.tsx, src/frontend/src/mobile/pages/EditarPerfil.tsx, src/frontend/src/mobile/pages/Login.tsx, src/frontend/src/mobile/pages/OutrosPerfis.tsx, src/frontend/src/mobile/pages/Perfil.tsx, src/frontend/src/mobile/pages/VisualizarUsuarios.tsx, src/frontend/src/services/axiosConfig.ts, src/frontend/src/services/tokenConfig.ts
* Auth-Service
* Criação de model para devolver info de usuários que já incui as infos das tabelas da role espefica do usuário
* Arrumar estrutura do texto do email de recuperar senha
* Separar rota de um usuário se atualizar e a rota de um admin atualizar algum usuário
* Ajuste rota PegarUsuario e WhoIAm para devolver os novos models
* Property-service
* AJuste no CORS
* Front
* Criação de um componentes chamado FormFieldFilter que é quase igual FormField só que com algumas alterações para facilitar no filtro dinâmico de alguns lugares que usamos filtro, como a tela de visualizar todos usuários
* Integração tela EditarPerfil
* Integração tela OutrosPerfis
* Integração tela Perfil
* Integração tela Visualizar todos usuários
* Função no front para devolver as infos do JWT
closes #219 #220 …
=> Integracao telas usuarios

src/Property-service/Layer.Application/Models/NewImoveis.cs, src/frontend/src/components/Form/FormField.tsx, src/frontend/src/desktop/components/Form/FormField.tsx, src/frontend/src/desktop/pages/CreateProperty.tsx, src/frontend/src/mobile/pages/CreateProperty.tsx, src/frontend/src/services/apiService.ts
- Alterei ImoveisModel para que locatario_id e locador_id fossem opcionais
- Configurei novamente o apiService.ts para o novo serviço de property
- Adicionei o fetch com axiosInstance para a criação de imóveis
- Alterei os inputs do forms utilizando FormField (desktop, nos dois casos) para que o handleSubmit funcionasse corretamente
Observações:
- As rotas configuradas já se referem às rotas do gateway
- O formulário precisa incluir mais dois inputs para relacionar locador e locatário ao novo imóvel criado
- Os inputs nas versões de desktop e mobile estão utilizando o FormField Desktop (o formfield mobile simplesmente não estava funcional)
closes #218
=> Integra página de criação de imóveis (desktop e mobile)

src/Property-service/Layer.Application/Controllers/ChamadosController.cs, src/Property-service/Layer.Application/Models/NewChamado.cs, src/Property-service/Layer.Domain/Entites/Chamados.cs, src/frontend/src/desktop/pages/CreateTicket.tsx, src/frontend/src/mobile/pages/CreateTicket.tsx
Tive que mexer em algumas coisas no serviço também ái demorou um pouco mais
=> Integrando tela de criar chamados

src/frontend/.gitignore, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/desktop/pages/Login.tsx, src/frontend/src/mobile/pages/Chamado.tsx, src/frontend/src/mobile/pages/Login.tsx, src/frontend/src/services/axiosConfig.ts, src/frontend/tsconfig.json
---
- configura a leitura do url base a partir do .env e realiza adaptações necessárias
- integra página de login no desktop
- atualiza as rotas em que o front faz o fetch
- corrige um erro de build por tipagem do retorno de uma funcao (pertence à página de chamados)
closes: #259
=> Integra a página de login no desktop

src/Payment-service/Layer.Application/Controllers/PaymentController.cs, src/Payment-service/Layer.Domain/Entities/Contratos.cs, src/Payment-service/Layer.Domain/Interfaces/IPaymentService.cs, src/Payment-service/Layer.Infrastructure/Database/ApplicationDbContext.cs, src/Payment-service/Layer.Services/Services/PaymentService.cs, src/Property-service/Layer.Application/Controllers/ChamadosController.cs, src/Property-service/Layer.Application/Controllers/ImoveisController.cs, src/Property-service/Layer.Domain/Interfaces/IimoveisRepository.cs, src/Property-service/Layer.Services/Services/ChamadosService.cs, src/Property-service/Layer.Services/Services/ImoveisService.cs
- Update property service for show infos about a property by id 'locador' and 'locatário'
- Update payment service for show infos about payments by propery id.
#284
=> FEAT | property infos and payments for frontend

src/frontend/src/desktop/components/CardImovel.tsx, src/frontend/src/desktop/components/Imoveis.tsx, src/frontend/src/mobile/components/Imoveis/Card.tsx, src/frontend/src/mobile/pages/VisualizarImoveis.tsx
- Adicionando integração com a tela de imóveis para rederizar imóveis tanto na tela desktop, quanto na mobile.
=> FEAT | integration imoveis

src/Property-service/Layer.Application/Controllers/ImoveisController.cs
- Adiciona endpoint para pegar as informações de um determinado imóvel por id com verificação do token para locatário ou locador.
=> add: getImoveisById with verification for 'locatario' or 'locador'

src/frontend/src/desktop/pages/CreateUser.tsx, src/frontend/src/mobile/pages/CreateUser.tsx, src/frontend/src/mobile/pages/VisualizarUsuarios.tsx
=> FIX | dynamic user creation page

src/frontend/src/components/Form/ContractForm.tsx
- names of renters and lessors on contract form
=> FIX | names of renters and lessors on contract form

src/frontend/src/components/Loading.tsx, src/frontend/src/mobile/pages/dashboard/BarChart.tsx, src/frontend/src/mobile/pages/dashboard/Dashboard.tsx, src/frontend/src/mobile/pages/dashboard/LineChart.tsx
- Modifica o componente de indicador de carregamento para aceitar mais props e exibir outros carregamentos;
- Adiciona o componete de carregamento nos componentes de gráfico para exibi-lo em vez de uma string;
- Modifica o auto-redimensionamento dos gráficos;
- Melhora a estilização da visualização dos dados.
=> style: melhora estilização da página de dashboard

src/frontend/src/desktop/pages/Login.tsx, src/frontend/src/mobile/pages/Login.tsx
- add: improve login with trim function
=> FEAT | improve login with trim function

src/Auth-service/Layer.Application/Program.cs
- Add System.Text.Json.Serialization.ReferenceHandler into Auth Service for fix cycle dependency on create admin user
=> FIX | cicle dependency on create admin user

src/Property-service/Layer.Application/Controllers/ContratosController.cs, src/Property-service/Layer.Application/Program.cs, src/Property-service/Layer.Domain/Interfaces/IContratosRepository.cs, src/Property-service/Layer.Services/Services/ContratoService.cs, src/frontend/src/components/Form/ContractForm.tsx, src/frontend/src/mobile/pages/ContractView.tsx, src/frontend/src/mobile/pages/CreateContract.tsx
Agora da pra criar contratos com documentos associados e remover documentos dos contratos já criados.
=> FIX | documents
